version: 0.0
os: linux
files:
  - source: /src
    destination: /home/ubuntu
  - source: /scripts
    destination: /home/ubuntu/darkskyweather
hooks:
  AfterInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root